### ISSUE TITLE
Spelling errors in the Docs

### ISSUE THREAD

**Issue by pratikpatil2001** [berachain/guides#79]
https://docs.berachain.com/learn/pol/incentives
in the incentives section of Proof of Liquidity section of docs there is a header "How To Whitelist Incentive Assets" .
in that section in second line it is having "based on the their" which should be "based on their"
correction is remove "the "

**Comment by pratikpatil2001** [comment]
Also in the same section in first line it is having "create via successful" which should be "created via successful"

should be created not create

**Comment by imanpajand** [comment]
appreciate it.
